// Lightweight index of every published blog post — powers /blog, related-post
// lookups, and generateStaticParams without importing full post bodies.
// Appended to (by the orchestrator, not the writer subagent) after each batch.
// Keep in sync with public/sitemap.xml and content/blog/TOPIC-BACKLOG.md.
import type { BlogManifestEntry } from "./types";

export const blogManifest: BlogManifestEntry[] = [
  {
    slug: "news-media-the-features-every-news-media-website-needs-in-nigeria",
    title: "The Features Every News & Media Website Needs in Nigeria",
    excerpt: "A news site that loads slowly, gets missed by AI search, or can't handle a traffic spike on a big story isn't a news site \u2014 it's a liability. Here's what actually has to be built in.",
    category: "industry-vertical",
    targetKeyword: "news & media website features",
    publishDate: "2025-11-04",
  },
  {
    slug: "how-much-does-a-business-website-cost-in-nigeria-in-2026",
    title: "How Much Does a Business Website Cost in Nigeria in 2026?",
    excerpt: "The honest answer is: it depends on what the website has to do for your business \u2014 but here are the real tiers, what drives the price inside each one, and where most businesses overpay or underspend.",
    category: "cost-pricing",
    targetKeyword: "business website cost nigeria 2026",
    publishDate: "2025-11-04",
  },
  {
    slug: "case-study-hr-onboarding-automation",
    title: "HR Onboarding Automation: Inside the Build",
    excerpt: "New hires used to mean a week of manual checklists, chased documents, and someone remembering to set up accounts. Here's how that entire process gets automated end to end.",
    category: "case-study",
    targetKeyword: "hr onboarding automation case study",
    publishDate: "2025-11-05",
  },
  {
    slug: "retail-pos-how-ai-automation-is-changing-retail-pos-in-nigeria",
    title: "How AI Automation Is Changing Retail & POS in Nigeria",
    excerpt: "Retail businesses in Nigeria are moving past 'a POS that prints receipts' toward systems that manage inventory, follow up with customers, and flag problems automatically \u2014 here's what that actually looks like.",
    category: "industry-vertical",
    targetKeyword: "ai automation retail & pos nigeria",
    publishDate: "2025-11-06",
  },
  {
    slug: "seo-aeo-seo-aeo-a-practical-checklist-before-you-start",
    title: "SEO & AEO: A Practical Checklist Before You Start",
    excerpt: "Most businesses jump into content and ads before fixing the technical basics that decide whether Google \u2014 or ChatGPT \u2014 can even find and trust the site. Here's the order that actually works.",
    category: "service",
    targetKeyword: "seo & aeo checklist nigeria",
    publishDate: "2025-11-06",
  },
  {
    slug: "case-study-school-management-system",
    title: "School Management System: Inside the Build",
    excerpt: "A school running on paper registers and separate spreadsheets for grades and attendance loses information every term. Here's how a single connected system replaces all of it.",
    category: "case-study",
    targetKeyword: "school management system case study",
    publishDate: "2025-11-07",
  },
  {
    slug: "what-affects-the-cost-of-a-saas-platform-in-nigeria",
    title: "What Affects the Cost of a SaaS Platform in Nigeria?",
    excerpt: "SaaS pricing questions almost always get answered with a single number, which is the wrong answer \u2014 the real answer is a list of decisions that each move the price. Here's that list.",
    category: "cost-pricing",
    targetKeyword: "saas platform price factors nigeria",
    publishDate: "2025-11-07",
  },
  {
    slug: "ecommerce-e-commerce-website-development-in-nigeria-the-complete-guide",
    title: "E-commerce Website Development in Nigeria: The Complete Guide",
    excerpt: "Most e-commerce sites in Nigeria fail on payments, logistics visibility, or mobile speed \u2014 not on design. Here's what actually needs to be right before launch.",
    category: "industry-vertical",
    targetKeyword: "e-commerce website development nigeria",
    publishDate: "2025-11-07",
  },
  {
    slug: "case-study-royal-quran-competition",
    title: "Royal Quran Competition: Inside the Build",
    excerpt: "A competition with real-time scoring and open registration needs infrastructure that a signup form and a spreadsheet can't provide. Here's how that platform was built.",
    category: "case-study",
    targetKeyword: "royal quran competition case study",
    publishDate: "2025-11-09",
  },
  {
    slug: "ai-automation-how-ai-automation-whatsapp-agents-actually-works-a-step-by-step",
    title: "How AI Automation & WhatsApp Agents Actually Works: A Step-by-Step Breakdown",
    excerpt: "A WhatsApp AI agent isn't a chatbot with scripted replies \u2014 it's a system that reads intent, pulls real data, and takes action. Here's exactly how that pipeline works.",
    category: "service",
    targetKeyword: "how ai automation & whatsapp agents works",
    publishDate: "2025-11-09",
  },
  {
    slug: "case-study-suap-ng-crypto-trading",
    title: "Suap.ng - Crypto Trading: Inside the Build",
    excerpt: "A crypto trading platform has to be fast, accurate on live prices, and unforgiving on security at the same time. Here's how those three requirements get built together.",
    category: "case-study",
    targetKeyword: "suap.ng - crypto trading case study",
    publishDate: "2025-11-10",
  },
  {
    slug: "what-questions-should-i-ask-before-hiring-a-web-developer",
    title: "What Questions Should I Ask Before Hiring a Web Developer?",
    excerpt: "Price is the question most business owners lead with, and it's the least useful one. These are the questions that actually separate a developer who delivers from one who disappears after launch.",
    category: "how-to",
    targetKeyword: "questions to ask before hiring a web developer",
    publishDate: "2025-11-13",
  },
  {
    slug: "news-media-how-much-does-a-news-media-website-cost-in-nigeria",
    title: "How Much Does a News & Media Website Cost in Nigeria?",
    excerpt: "A news website's price isn't just about pages \u2014 it's about infrastructure that survives a breaking story, a CMS a newsroom can actually publish from, and monetization built in. Here's what drives the number.",
    category: "industry-vertical",
    targetKeyword: "news & media website cost nigeria",
    publishDate: "2025-11-13",
  },
  {
    slug: "sales-funnels-how-sales-funnels-actually-works-a-step-by-step-breakdown",
    title: "How Sales Funnels Actually Works: A Step-by-Step Breakdown",
    excerpt: "A sales funnel isn't a landing page with a form on it \u2014 it's a connected sequence of pages, automation and follow-up designed to turn a stranger into a booked customer. Here's how each stage works.",
    category: "service",
    targetKeyword: "how sales funnels works",
    publishDate: "2025-11-13",
  },
  {
    slug: "ai-automation-how-much-does-ai-automation-whatsapp-agents-cost-in-nigeria",
    title: "How Much Does AI Automation & WhatsApp Agents Cost in Nigeria?",
    excerpt: "The cost question almost always gets asked before the scope question, which is backwards \u2014 here's what actually drives the price of a WhatsApp AI agent or automation system in Nigeria.",
    category: "service",
    targetKeyword: "ai automation & whatsapp agents cost nigeria",
    publishDate: "2025-11-14",
  },
  {
    slug: "what-is-schema-markup-and-why-does-it-matter-for-ai-search",
    title: "What Is Schema Markup and Why Does It Matter for AI Search?",
    excerpt: "Schema markup is invisible to your site visitors and increasingly the single biggest factor in whether ChatGPT, Perplexity or Google AI Overviews ever mention your business. Here's what it actually is.",
    category: "how-to",
    targetKeyword: "what is schema markup ai search",
    publishDate: "2025-11-16",
  },
  {
    slug: "what-makes-a-website-high-converting",
    title: "What Makes a Website 'High-Converting'?",
    excerpt: "A beautiful website and a high-converting website are two different things, and businesses regularly pay for one while needing the other. Here's what actually separates them.",
    category: "how-to",
    targetKeyword: "what makes a website high converting",
    publishDate: "2025-11-16",
  },
  {
    slug: "case-study-lead-qualification-ai-bot",
    title: "Lead Qualification AI Bot: Inside the Build",
    excerpt: "Sales teams waste hours chasing leads that were never going to close. Here's how an AI system scores and routes leads automatically, so reps only work the ones worth working.",
    category: "case-study",
    targetKeyword: "lead qualification ai bot case study",
    publishDate: "2025-11-16",
  },
  {
    slug: "how-to-hire-a-web-development-agency-in-ghana",
    title: "How to Hire a Web Development Agency in Ghana",
    excerpt: "Ghanaian businesses don't have to limit their search to agencies physically based in Accra or Kumasi \u2014 the right remote partner can deliver more than a local shop with a smaller portfolio. Here's how to evaluate either.",
    category: "geography",
    targetKeyword: "web development agency ghana",
    publishDate: "2025-11-16",
  },
  {
    slug: "best-web-developer-in-tanzania-a-buyer-s-guide",
    title: "Best Web Developer in Tanzania: A Buyer's Guide",
    excerpt: "There's no single 'best' developer in Tanzania \u2014 there's the developer whose verified work matches what your business actually needs. Here's how to find that developer.",
    category: "geography",
    targetKeyword: "best web developer tanzania",
    publishDate: "2025-11-19",
  },
  {
    slug: "e-commerce-website-pricing-for-small-businesses-vs-enterprises-in",
    title: "E-commerce Website Pricing for Small Businesses vs Enterprises in Nigeria",
    excerpt: "A ten-product store and a multi-warehouse retail platform are both 'e-commerce websites,' but pricing them the same way misleads both buyers. Here's where the real difference sits.",
    category: "cost-pricing",
    targetKeyword: "e-commerce website pricing nigeria",
    publishDate: "2025-11-19",
  },
  {
    slug: "case-study-cascadia-holdings",
    title: "Cascadia Holdings: Inside the Build",
    excerpt: "An investment holdings company's website has to do something most corporate sites don't \u2014 earn trust from people deciding whether to put money into it. Here's how that gets built.",
    category: "case-study",
    targetKeyword: "cascadia holdings case study",
    publishDate: "2025-11-21",
  },
];
