// Site Configuration
// Update this file with your personal information

export const siteConfig = {
  // Personal Info
  name: "Abdul-Azeez Agbona",
  title: "IT Specialist & Web Development Expert",
  bio: "A versatile IT Specialist with over 10 years of experience in web development, e-commerce, digital marketing, and IT consulting for individuals, businesses, and government entities across various sectors.",
  email: "azeez.agbona.o@gmail.com",
  location: "Lagos, Nigeria",
  phone: "07069716822",
  whatsapp: "https://wa.me/2347069716822?text=Hello%20Abdul-Azeez,%20I%20found%20your%20portfolio%20and%20would%20like%20to%20discuss%20a%20project%20with%20you.",
  website: "https://harzotech.com.ng",

  // Professional Stats
  stats: {
    yearsExperience: "10+",
    projectsCompleted: "20+",
    happyClients: "20+",
    technologies: "10+",
  },

  // About Section
  about: {
    description: [
      "I am a versatile IT Specialist with over 10 years of experience in web development, e-commerce, digital marketing, and IT consulting for individuals, businesses, and government entities across various sectors. Adept at developing web applications, optimizing digital marketing strategies, and creating effective sales funnels and business models.",
      "Expert in building high-converting sales funnel systems that drive business growth. Successfully designed and implemented comprehensive sales funnel solutions for leading healthcare brands including Exclusive Smile Lagos and Phoenix Derma Lagos, integrating marketing automation, CRM systems, and conversion optimization strategies.",
      "Skilled in leading IT teams, managing complex projects, and delivering tailored solutions that enhance operational efficiency and drive business growth. Strong communicator with a proven track record of managing client relationships and delivering innovative technical solutions.",
    ],
  },

  // Skills
  skills: {
    frontend: ["HTML", "CSS", "JavaScript", "WordPress", "React", "Next.js", "Vite", "Tailwind CSS", "Thrive Architect"],
    backend: ["PHP", "Laravel", "MySQL", "SQL", "Node.js", "RESTful API", "API Development", "Database Design", "Database Management"],
    tools: ["Google Analytics", "SEMrush", "Ahrefs", "Yoast SEO", "Google Ads", "Google Search Console", "Screaming Frog SEO Spider", "Mailchimp", "Active Campaign", "Get Response", "Google Trends"],
    dataScience: ["Machine Learning", "Deep Learning", "Data Analysis", "Big Data Analytics", "Machine Learning Applications"],
    professional: ["Leadership & Team Management", "Project Management", "Client Relationship Management", "Critical Thinking", "Problem Solving", "Communication & Collaboration", "Strategic Thinking", "Business Development", "Techpreneurship", "Business Model Development"],
    technical: ["SEO Optimization", "Digital Marketing Strategies", "Sales Funnel Systems", "Software Development", "Technical Support", "IT Support", "CRM Systems", "ERP Systems", "Technical Analysis"],
  },

  // Projects
  projects: [
    {
      title: "R3 Consulting Ltd",
      description: "Corporate consulting website with client portal, project management tools, and business intelligence dashboard.",
      tags: ["Next.js", "Laravel", "Dashboard"],
      gradient: "from-indigo-600 to-purple-600",
      image: "/project/r3consulting.png",
      liveUrl: "https://r3consultingltd.com",
      githubUrl: "#",
    },
    {
      title: "Suko Paint",
      description: "E-commerce platform for premium paint products with color visualizer, dealer locator, and project calculator.",
      tags: ["Next.js", "E-commerce", "Product Catalog"],
      gradient: "from-pink-600 to-rose-600",
      image: "/project/sukopaint.png",
      liveUrl: "https://www.sukopaint.com",
      githubUrl: "#",
    },
    {
      title: "Restopro - Restaurant Management",
      description: "SaaS restaurant management system with table reservation, order management, kitchen display, and payment integration.",
      tags: ["Laravel", "Blade", "Vite", "REST API"],
      gradient: "from-purple-600 to-pink-600",
      image: "/project/restopro.png",
      liveUrl: "https://restaurant.cliqpos.co.uk",
      githubUrl: "#",
    },
    {
      title: "Immovables Realty",
      description: "Premium real estate marketplace with advanced property search, agent profiles, and mortgage calculators.",
      tags: ["React", "Vite", "Real Estate"],
      gradient: "from-teal-600 to-cyan-600",
      image: "/project/immovablesrealty.png",
      liveUrl: "https://www.immovablesrealty.com",
      githubUrl: "#",
    },
    {
      title: "Access Best Empowerment Hub",
      description: "Educational platform empowering communities with training programs, certifications, and skill development resources.",
      tags: ["React", "Vite", "LMS"],
      gradient: "from-cyan-600 to-blue-600",
      image: "/project/accessbest.png",
      liveUrl: "https://accessbest.com.ng",
      githubUrl: "#",
    },
    {
      title: "Cliqpos - SaaS POS System",
      description: "Cloud-based Point-of-Sale system serving multiple businesses with real-time inventory, sales tracking, and multi-location support.",
      tags: ["Laravel", "Blade", "Vite", "MySQL"],
      category: "Retail",
      type: "SaaS",
      gradient: "from-blue-600 to-cyan-600",
      image: "/project/cliqpos.png",
      liveUrl: "https://cliqpos.co.uk",
      githubUrl: "#",
    },
    {
      title: "Interop Digital Solutions Ltd",
      description: "Enterprise digital transformation platform providing software solutions, consulting, and integration services.",
      tags: ["Next.js", "TypeScript", "Enterprise"],
      gradient: "from-indigo-600 to-blue-600",
      image: "/project/interopdigital.png",
      liveUrl: "https://interop-digital-solutions-ltd.vercel.app",
      githubUrl: "#",
    },
    {
      title: "Immovables Group",
      description: "Full-stack real estate platform with property listings, virtual tours, and integrated CRM for Nigeria's leading property group.",
      tags: ["Next.js", "Laravel", "RESTful API"],
      gradient: "from-green-600 to-teal-600",
      image: "/project/immovablesgroup.png",
      liveUrl: "https://immovablesgroup.com",
      githubUrl: "#",
    },
    {
      title: "Immovables Digital Space",
      description: "Technology solutions platform showcasing digital services, software development, and IT consulting offerings.",
      tags: ["WordPress", "Custom Theme", "Digital Solutions"],
      gradient: "from-blue-600 to-purple-600",
      image: "/project/immovablestech.png",
      liveUrl: "https://immovablestech.com",
      githubUrl: "#",
    },
    {
      title: "Alajo - Savings Platform",
      description: "Digital savings and investment platform with secure transactions, automated savings, and financial analytics.",
      tags: ["Next.js", "Laravel", "Payment Integration"],
      gradient: "from-orange-600 to-red-600",
      image: "/project/alajo.png",
      liveUrl: "https://alajo.ng",
      githubUrl: "#",
    },
    {
      title: "The Pen Muslim Montessori School",
      description: "Educational institution website with admissions portal, student information system, and parent communication tools.",
      tags: ["Vite", "React", "Education"],
      gradient: "from-green-600 to-emerald-600",
      image: "/project/thepen.png",
      liveUrl: "https://thepenmuslimschools.com",
      githubUrl: "#",
    },
    {
      title: "Polygrace Home Healthcare",
      description: "Healthcare management platform for Canadian home care services with patient scheduling and care coordination.",
      tags: ["Vite", "Healthcare", "Scheduling"],
      gradient: "from-emerald-600 to-green-600",
      image: "/project/polygrace.png",
      liveUrl: "https://www.polygracehomehealthcare.ca",
      githubUrl: "#",
    },
    {
      title: "Growth Vault",
      description: "Business growth and marketing automation platform with funnel builder, email campaigns, and analytics.",
      tags: ["Next.js", "Automation", "Marketing"],
      gradient: "from-violet-600 to-purple-600",
      image: "/project/growthvault.png",
      liveUrl: "https://growth-vault-launch.vercel.app",
      githubUrl: "#",
    },
    {
      title: "Majestic Services UK",
      description: "Professional cleaning and facility management services platform with booking system and service tracking.",
      tags: ["Vite", "React", "Service Platform"],
      gradient: "from-blue-600 to-cyan-600",
      image: "/project/majesticservices.png",
      liveUrl: "https://www.majesticservices.co.uk",
      githubUrl: "#",
    },
    {
      title: "Royal Quran Competition",
      description: "Islamic competition platform with registration system, scoring interface, and event management for Quranic excellence.",
      tags: ["Next.js", "Event Management", "Competition"],
      gradient: "from-purple-600 to-indigo-600",
      image: "/project/royalquran.png",
      liveUrl: "https://royal-quran-shine.vercel.app",
      githubUrl: "#",
    },
    {
      title: "Business Revival Webinar",
      description: "Webinar and event management platform for business training programs with registration and live streaming.",
      tags: ["Next.js", "Webinar", "Event Platform"],
      gradient: "from-orange-600 to-amber-600",
      image: "/project/businessrevival.png",
      liveUrl: "https://webinar.immovablestech.com",
      githubUrl: "#",
    },
    {
      title: "Strategic Effects Ltd",
      description: "Corporate consulting and strategy firm website showcasing services, case studies, and client success stories.",
      tags: ["WordPress", "Corporate", "Consulting"],
      gradient: "from-slate-600 to-gray-600",
      image: "/project/strategiceffects.png",
      liveUrl: "https://strategiceffectsltd.com",
      githubUrl: "#",
    },
    {
      title: "Lagos Chamber of Commerce",
      description: "Membership portal and arbitration platform for LACIAC, serving thousands of businesses across Lagos State.",
      tags: ["WordPress", "Custom Development", "Member Portal"],
      gradient: "from-pink-600 to-rose-600",
      image: "/project/Laciac.png",
      liveUrl: "https://laciac.org",
      githubUrl: "#",
    },
    {
      title: "Harzotech Nig Ltd",
      description: "IT consulting and software development company website showcasing services, portfolio, and technology expertise.",
      tags: ["WordPress", "IT Services", "Corporate"],
      gradient: "from-cyan-600 to-teal-600",
      image: "/project/harzotech.png",
      liveUrl: "https://harzotech.com.ng",
      githubUrl: "#",
    },
    {
      title: "Suap.ng - Crypto Trading",
      description: "Cryptocurrency trading platform with real-time market data, secure wallet integration, and trading tools.",
      tags: ["Laravel", "Crypto", "Trading Platform"],
      gradient: "from-yellow-600 to-orange-600",
      image: "/project/suap.png",
      liveUrl: "https://suap.ng",
      githubUrl: "#",
    },
    {
      title: "Exclusive Smile Nigeria",
      description: "Dental clinic and healthcare platform with appointment booking, patient records, and comprehensive sales funnel system integrating marketing automation, lead nurturing, and conversion optimization.",
      tags: ["Next.js", "Sanity CMS", "Airtable", "SendPulse", "Sales Funnel"],
      gradient: "from-blue-600 to-indigo-600",
      image: "/project/exclusivesmile.png",
      liveUrl: "https://www.exclusivesmileng.com",
      githubUrl: "#",
    },
    {
      title: "Phoenix Derma Lagos",
      description: "Premium dermatology and skincare clinic with advanced sales funnel system, automated patient acquisition, booking system, and integrated marketing campaigns for skincare services.",
      tags: ["Sales Funnel", "Marketing Automation", "Healthcare"],
      gradient: "from-rose-600 to-pink-600",
      image: "/project/phoenixderma.png",
      liveUrl: "#",
      githubUrl: "#",
    },
    {
      title: "Brand Tune",
      description: "Creative brand jingle and audio branding platform for businesses seeking memorable sonic identities.",
      tags: ["Web Development", "Multimedia", "Branding"],
      gradient: "from-fuchsia-600 to-pink-600",
      image: "/project/brandtune.png",
      liveUrl: "#",
      githubUrl: "#",
    },
    {
      title: "Crypto Trading App",
      description: "Advanced cryptocurrency trading application with real-time charts, portfolio tracking, and secure transactions.",
      tags: ["Laravel", "Blockchain", "Trading"],
      gradient: "from-amber-600 to-yellow-600",
      image: "/project/cryptoapp.png",
      liveUrl: "#",
      githubUrl: "#",
    },
    {
      title: "New Telegraph Newspaper",
      description: "Major Nigerian news publication platform with breaking news, multimedia content, and digital subscriptions.",
      tags: ["WordPress", "News Portal", "Media"],
      gradient: "from-red-600 to-orange-600",
      image: "/project/newtelegraph.png",
      liveUrl: "https://newtelegraphng.com",
      githubUrl: "#",
    },
    {
      title: "Yuan Bridge - Naira to Yuan Flow",
      description: "Currency exchange platform facilitating seamless Naira to Yuan conversions with real-time rates and secure transactions.",
      tags: ["Next.js", "FinTech", "Currency Exchange"],
      gradient: "from-emerald-600 to-teal-600",
      image: "/project/yuanbridge.png",
      liveUrl: "https://naira-yuan-flow.vercel.app/",
      githubUrl: "#",
    },
    {
      title: "Hotel Management System",
      description: "Comprehensive hotel management solution with booking engine, room management, POS integration, and guest services.",
      tags: ["Laravel", "MySQL", "Hospitality"],
      gradient: "from-red-600 to-pink-600",
      liveUrl: "#",
      githubUrl: "#",
    },
    {
      title: "School Management System",
      description: "Complete school administration platform with student records, attendance tracking, grades, and parent communication.",
      tags: ["Laravel", "MySQL", "Education"],
      gradient: "from-green-600 to-lime-600",
      liveUrl: "#",
      githubUrl: "#",
    },
    {
      title: "Multi-Tenancy SaaS Platform",
      description: "Scalable SaaS application architecture supporting multiple tenants with isolated data and customizable features.",
      tags: ["Laravel", "Multi-Tenancy", "SaaS"],
      gradient: "from-sky-600 to-blue-600",
      liveUrl: "#",
      githubUrl: "#",
    },
  ],

  // Social Links
  social: {
    github: "https://github.com/agbona24/",
    linkedin: "https://www.linkedin.com/in/azeez-agbona-o/",
    twitter: "https://twitter.com/azeez_agbona1",
    instagram: "https://www.instagram.com/abdulAbdul-Azeezagbona/",
    facebook: "https://web.facebook.com/agbona.azeez/",
    whatsapp: "https://wa.me/2347069716822?text=Hello%20Abdul-Azeez,%20I%20found%20your%20portfolio%20and%20would%20like%20to%20discuss%20a%20project%20with%20you.",
    email: "mailto:azeez.agbona.o@gmail.com",
  },

  // Testimonials
  testimonials: [
    {
      name: "Dr. Sarah Johnson",
      role: "Founder, Business Growth Hub",
      company: "Business Growth Hub",
      content: "Abdul-Azeez's sales funnel system transformed our patient acquisition. We saw a 300% increase in qualified leads within 3 months. His expertise in healthcare marketing is exceptional.",
      rating: 5,
    },
    {
      name: "Jude Afuda-iyoke",
      role: "Managing Director/CEO, Immovables Group",
      company: "Immovables Group",
      content: "Outstanding work on our real estate platform. The CRM integration and property management system exceeded expectations. Highly professional and delivered on time.",
      rating: 5,
    },
    {
      name: "Olusesan Sesan",
      role: "MD, Lagos Chamber of Commerce",
      company: "LACIAC",
      content: "Developed a robust membership portal that serves thousands of businesses. Abdul-Azeez's technical expertise and understanding of our needs made the project a huge success.",
      rating: 5,
    },
    {
      name: "Yusuf Adegbola",
      role: "Owner, Majestic Services UK",
      company: "Majestic Services",
      content: "The booking system and service tracking platform has streamlined our operations significantly. Excellent communication throughout the project.",
      rating: 5,
    },
    {
      name: "Mr. Gideon Makinwa",
      role: "MD, R3 Consulting",
      company: "R3 Consulting Ltd",
      content: "Abdul-Azeez delivered a comprehensive consulting platform that transformed our business operations. His technical expertise and strategic approach made the entire process seamless.",
      rating: 5,
    },
    {
      name: "Mr. Ikenna",
      role: "CEO, Access Best Empowerment Hub",
      company: "Access Best Empowerment Hub",
      content: "Working with Abdul-Azeez on our educational platform was exceptional. He understood our vision and created a robust system that empowers thousands of learners across communities.",
      rating: 5,
    },
    {
      name: "Mr. Yemi Dada",
      role: "Managing Partner, Alajo.ng",
      company: "Alajo.ng",
      content: "He is a great partner and one of the best at what he does. The savings platform he developed has been instrumental in our success and growth.",
      rating: 5,
    },
    {
      name: "Mr. Akinbobola",
      role: "Chairman, Exclusive Smile",
      company: "Exclusive Smile Nigeria",
      content: "Our sales funnel was implemented and did well. Abdul-Azeez's marketing automation system significantly improved our patient acquisition and conversion rates.",
      rating: 5,
    },
  ],

  // Contact Form
  contact: {
    // Using Web3Forms (free service)
    // Sign up at https://web3forms.com to get your access key
    web3formsAccessKey: "YOUR_WEB3FORMS_ACCESS_KEY",
  },

  // Resume
  resume: {
    // Place your resume PDF in public/resume.pdf
    url: "/resume.pdf",
  },

  // SEO
  seo: {
    title: "Abdul-Azeez Agbona - IT Specialist & Web Development Expert",
    description: "10+ years experience in web development, SEO, digital marketing, and IT consulting. Specializing in Laravel, WordPress, ERP systems, and business solutions.",
    url: "https://harzotech.com.ng",
    image: "/headshot.jpg",
  },
};

export type SiteConfig = typeof siteConfig;
